---
title: "Tests of BDL Bias and Variance - v.1a"
author:
  - name: James R. Hunter, D.Sc.
    affiliation: Laboratório de Retrovirologia, UNIFESP
date: last-modified

format: 
  typst: 
    mainfont: "Nunito"
    fontsize: 11pt

editor: visual

execute:
  echo: false
  warning: false
  message: false
bibliography: references.bib
---

## Purpose

This file will test the determination of bias and variance when calculating viral loads and other variables that are subject to detection limits. For HIV-1 patients, the objective of antiretroviral treatment is to make their plasma RNA viral load zero.

However, there is a practical limit below which the assays cannot distinguish between the presence of virus and having no virus (the zero objective). This is called the "detection limit" and patients who achieve this level are said to have a viral load "BDL", below detection limit. One of the most important consequences of exactitude in measuring true lack of the presence of virus is the phrase "undetectable = untransmittable" [@chang2025][@combescure2009]. This frees, at least emotionally, the individual from concern about transmitting the virus to a partner.

There have been various strategies to deal with calculations of viral load in a panel of patients. One has been to eliminate the cases from the calculation, another has been to treat the viral level of those patients who are BDL as 0, assuming they are really without any virus. Still another strategy has been to assign a value equal to the detection limit. Others have used a value of half the detection limit, i.e., half of the difference between the detection limit and zero.

| Name   | Strategy                         | Value Assigned to "BDL" |
|--------|----------------------------------|-------------------------|
| censor | eliminate case                   | no value                |
| zero   | treat as zero                    | 0                       |
| dl     | treat as detection limit         | detection limit         |
| halfdl | treat as half of detection limit | detection limit/2       |

: Table 1: Strategies for Handling BDL Values

This study was inspired by a blog post by Nikolas Siccha, "Lower Limits of Detection or Quantification".[@siccha2025] He develops a Bayesian model to explore the pharmacodynamics of drugs that cause the measurement of interest to fall below detection limits. As it deals with the dynamics over time of a drug's presence and efficacy in a patient, his question is more complex than the question I would like to address here.

::: callout-important
What is the relationship between the true value of viral load below detection limit and the strategies used to estimate it and how does that effect analyses of the viral load of a sample or population?
:::

## Method

I will create a panel of 1,000 PLWH artificially with estimates of their viral load at a baseline and after 48 simulated weeks of antiretroviral treatment (ART) when their viral load will have reduced to BDL, which I will define here as 50 copies per mL.[^1] According to a 2009 clinical trial (STARTMRK) of Raltegravir, a 1st generation integrase inhibitor, 86.1% of the RTG arm of naive patients had viral loads BDL by week 48. [@lennox2009] Likewise, a clinical trial (SINGLE) of a second generation integrase inhibitor, Dolutagravir, showed 88% of the DTG arm with viral loads below detection limit by week 48. [@walmsley2013] For my panel, I will use a proportion of 85% of patients achieving true viral loads between 0 and 50 by the 48 week mark. 85% is a bit more conservative than either of the real trials, but consistent with their results.

[^1]: While 50 copies was a common level for detection limit until 2024, since then it has been reduced to 30 or 20 copies depending on the measurement technology used. I am using 50 here as the purpose is to explore the bias and variance of samples rather than to test the detection limit itself.

The baseline viral loads will be determined by calculating 1,000 normal variates from a truncated normal distribution with a mean of 40,0000 copies per mL and a standard deviation of 42,000 copies. These values are estimated based on the Code Pharma Phase IIA trial of our lab (data not yet published). Since values below detection limit make no sense for this simulation, these values will be removed by using the truncated normal distribution.[@mersmann2023] By cutting off the negative values produced by the original calculation, the mean and standard deviation of the final set will be higher than the estimate from the Code Pharma clinical trial.

The 48 week data will be reduced by 92% and the number of values below 50 copies per mL will be calculated. I will then create a second version substituting the true values below the detection limit with BDL. Using the four strategies outlined in Table 1, I will then compare the bias and variance of each of these strategies for substituting the true value of the viral load. Finally, I will propose a method for imputing values that is commonly applied in studies using the R statistical language.

The flow chart below shows a schematic of the workflow of this study.

```{r}

#| label: determine_cohort_bl
#| echo: false

pacman::p_load(tidyverse, janitor, ggpubr, ggsci)
palettes <- readRDS("/Users/jameshunter/Documents/R/jim_palettes.rds")
stats <- c("mean", "sd", "min", "med", "max", "iqr", "cv")

set.seed(42)
## assumed values
n <- 1000
blmean <- 40000
blsd <- 42000
reduct_pct <- .92
dl <- 50

# calculate baseline distribution
bl <- truncnorm::rtruncnorm(n, mean = blmean, sd = blsd, a = dl)

# calculate summary stats
summarytools::descr(bl, stats = stats)

bldf <- as.data.frame(bl)
bldf |> 
  gghistogram(x = "bl",
              bins = 20,
              fill = palettes$jim_palette_1[1],
              title = "Viral Load Baseline Values - Simulated",
              xlab = "Viral Load",
              ggtheme = theme_bw())
```

The histogram shows that the viral loads for the cases are typically right-skewed, mirroring many studies of initial viral loads.
